### ISSUE TITLE
Adapting with KITTI-360

### ISSUE THREAD

**Issue by js0n-lai** [ActiveVisionLab/nope-nerf#18]
Hi,

Thanks for your work so far! I am interested in adapting NoPe-NeRF to the KITTI-360 dataset and in particular using LiDAR data as an alternative method for depth supervision and establishing sparse correspondences in challenging scenes. My YAML file is currently as below, where the data consists of ~100 posed images from the left camera.

```
dataloading:
  customized_focal: true
  customized_poses: true
  load_colmap_poses: false
  path: data/2013_05_28_drive_0000_sync
  random_ref: 1
  resize_factor: 1
  scene:
  - still_5
depth:
  type: None
distortion:
  learn_distortion: true
extract_images:
  eval_depth: true
  resolution:
  - 376
  - 1408
pose:
  init_R_only: false
  init_pose: false
  learn_R: true
  learn_focal: false
  learn_pose: true
  learn_t: true
  update_focal: true
training:
  auto_scheduler: true
  match_method: dense
  out_dir: out/kitti360/2013_05_28_drive_0000_sync/still_5
  use_gt_depth: false
  with_ssim: false
```
I had some questions:

1. When loading custom poses, what coordinate system is expected? The dataset uses (forward, left, up) for the camera-to-world transform. Furthermore, are these poses expected to be recentered and spherified as COLMAP poses are when loaded?
2. When `init_pose` is set to `true`, an `======invalid mask=====` message is printed throughout training, with the losses fluctuating significantly. What could be causing this? I suspect it could be due to either insufficient overlap in the training images ~~(colmap gui and img2poses from [LLFF](https://github.com/Fyusion/LLFF) both failed to generate poses for most images)~~ or the poses I supplied being in the incorrect coordinate system. 
3. When `init_pose` is set to `false`, what initial pose is used (assuming `load_colmap_poses` is `false`)?
4. How can pose refinement be disabled (e.g. to train using GT poses only)? I ran into errors setting `learn_pose` to `false` as `pose_param_net` gets set to `None` in `train.py`.
